export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_DONE_TASK = "TOGGLE_DONE_TASK";

export const FILTER_BY_NAME = "FILTER_BY_NAME";
export const FILTER_BY_EMAIL = "FILTER_BY_EMAIL";
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";

export const SORT_IN_ASCENDING_DIRECTION = "SORT_IN_ASCENDING_DIRECTION";
export const SORT_IN_DESCENDING_DIRECTION = "SORT_IN_DESCENDING_DIRECTION";
