export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_DONE_TASK = "TOGGLE_DONE_TASK";

export const SHOW_FORM = "SHOW_FORM";

export const FILTER_BY_FIELD = "FILTER_BY_FIELD";

export const SORT_IN_ASCENDING_DIRECTION = "SORT_IN_ASCENDING_DIRECTION";
export const SORT_IN_DESCENDING_DIRECTION = "SORT_IN_DESCENDING_DIRECTION";
